#!/bin/sh

fn_usage() {
	echo "Usage : $(basename "${0}") [USER_NAME] [TARGET]"
	exit 1
}

USER_NAME="${1}"
TARGET="${2}"

if [ -z "${USER_NAME}" -o -z "${TARGET}" -o -z "$(grep "^${USER_NAME}:" /etc/passwd)" -o ! -e "${TARGET}" ]; then
	fn_usage
	exit 1
fi

if [ "$(ls -land "${TARGET}" 2> /dev/null | sed -e 's/^[^ ]\+[ ]\+[^ ]\+[ ]\+\([^ ]\+\)[ ]\+\([^ ]\+\)[ ]\+.*$/\1:\2/g')" != "$(id -u ${USER_NAME}):$(id -g ${USER_NAME})" ]; then
	chown -R $(id -un ${USER_NAME}):$(id -gn ${USER_NAME}) "${TARGET}"
fi

